const ADD_TO_TRASH = 'trash/ADD_TO_TRASH';
const DELETE_FROM_TRASH = 'trash/DELETE_FROM_TRASH';
const DELETE_LABEL = 'trash/DELETE_LABEL';

export default {
  ADD_TO_TRASH,
  DELETE_FROM_TRASH,
  DELETE_LABEL
};
