const ADD_NOTE = 'ADD_NOTE';
const EDIT_NOTE = 'EDIT_NOTE';
const DELETE_NOTE = 'DELETE_NOTE';
const DELETE_LABEL_FROM_NOTE = 'DELETE_LABEL_FROM_NOTE';

export default {
  ADD_NOTE,
  EDIT_NOTE,
  DELETE_NOTE,
  DELETE_LABEL_FROM_NOTE
};
